In [1]:
from bvh_parser import BVH_file
import numpy as np

In [2]:
aBVH = BVH_file("Baseball Pitching.bvh")
# aBVH.write("try.BVH")
tryBVH = BVH_file("try.BVH")

q1s * q0s:  Quaternions([[ 0.74174872 -0.12946257 -0.64826403 -0.11314604]
 [ 0.74166658 -0.13022928 -0.64809026 -0.11379821]
 [ 0.74158771 -0.13098582 -0.64791493 -0.1144405 ]
 ...
 [ 0.73489459 -0.12585038 -0.65684021 -0.1124836 ]
 [ 0.73632493 -0.12372906 -0.65602203 -0.11023529]
 [ 0.73779221 -0.12150645 -0.65517655 -0.10790054]])
q1s * q0s:  Quaternions([[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]])
q1s * q0s:  Quaternions([[ 0.74174872 -0.12946257 -0.64826403 -0.11314604]
 [ 0.74166658 -0.13022928 -0.64809026 -0.11379821]
 [ 0.74158771 -0.13098582 -0.64791493 -0.1144405 ]
 ...
 [ 0.73489459 -0.12585038 -0.65684021 -0.1124836 ]
 [ 0.73632493 -0.12372906 -0.65602203 -0.11023529]
 [ 0.73779221 -0.12150645 -0.65517655 -0.10790054]])
q1s * q0s:  Quaternions([[ 0.97966735 -0.15359318  0.12751983  0.01999268]
 [ 0.97969986 -0.15328954  0.12763878  0.01997111]
 [ 0.9797496  -0.15297957  0.12763542  0.01992919]
 ...
 [ 0.9876505  -0.104803

In [9]:
print("aBVH.topology: ", len(aBVH.topology),aBVH.topology)
print(aBVH.offset.shape)
print("skeleton type: ",aBVH.skeleton_type)

aBVH.topology:  23 (0, 0, 1, 2, 3, 0, 5, 6, 7, 0, 9, 10, 11, 12, 13, 12, 15, 16, 17, 12, 19, 20, 21)
(23, 3)
skeleton type:  0


In [7]:
print(aBVH.anim.rotations.shape)
# print(tryBVH.anim.rotations[0])
motiontry = tryBVH.to_numpy(quater=False, edge=False)
print(motiontry.shape)
rotationstry = motiontry[..., :-3].reshape(motiontry.shape[0], -1, 3)
print(rotationstry.shape)

(313, 74, 3)
(313, 72)
(313, 23, 3)


In [5]:
motion = aBVH.to_numpy(quater=False, edge=False)
rotations = motion[..., :-3].reshape(motion.shape[0], -1, 3)
positions = motion[..., -3:]
print(rotations[0])
# print(positions.shape)

[[-1.9801004e+01 -8.2304784e+01 -2.1016957e+01]
 [-1.7820706e+01  1.4832582e+01  9.6036470e+00]
 [ 2.8144104e+01 -2.9956560e+00  5.0791050e+00]
 [-8.8265640e+00  1.2097090e+00 -7.1551740e+00]
 [ 0.0000000e+00  2.0000000e-06  0.0000000e+00]
 [-1.2955417e+01 -2.3320592e+01 -8.7279740e+00]
 [ 2.3074215e+01  8.7783470e+00 -8.8339400e+00]
 [-8.5745980e+00 -1.3413890e+00  1.1058311e+01]
 [ 0.0000000e+00 -1.0000000e-06 -0.0000000e+00]
 [-0.0000000e+00  0.0000000e+00 -0.0000000e+00]
 [ 2.2709800e+00  1.1504000e-01  7.1421000e-02]
 [ 4.5888510e+00  4.8045000e-02  1.5876490e+00]
 [ 4.5665000e+00  5.8995000e-02  1.6317790e+00]
 [-6.4494500e+00  9.1631340e+00 -4.2289880e+00]
 [ 1.3063320e+00  3.7856665e+01 -3.1278640e+00]
 [-2.3247500e-01  4.6378700e+00 -1.3596740e+00]
 [ 2.5122269e+01 -7.7231237e+01 -4.2206191e+01]
 [-8.0000000e-06 -1.4145783e+01 -1.0000000e-06]
 [-5.1489886e+01  1.6223470e+00  1.0545755e+01]
 [ 1.6129930e+00  4.3291750e+00  7.0436330e+00]
 [ 8.5951300e+00  2.5593740e+01  6.05795

In [1]:
import numpy as np
from Quaternion import *
from scipy.spatial.transform import Rotation as R
class kinect2BVH:
    def __init__(self, file_path):
        self.dic ={}
        self.corps_name = ['Pelvis', 'LeftUpLeg', 'LeftLeg', 'LeftFoot', 'LeftToeBase', 
                'RightUpLeg', 'RightLeg', 'RightFoot', 'RightToeBase', 
                'Hips', 'Spine', 'Spine1', 'Spine2', 'Neck', 'Head', 
                'LeftShoulder', 'LeftArm', 'LeftForeArm', 'LeftHand', 
                'RightShoulder', 'RightArm', 'RightForeArm', 'RightHand']
        self.topology = [0, 0, 1, 2, 3, 0, 5, 6, 7, 0, 9, 10, 
                         11, 12, 13, 12, 15, 16, 17, 12, 19, 20, 21]
        self.joint_num = len(self.topology)
        self.read_kinect_to_dic(file_path)
        self.offsets = np.zeros((self.joint_num, 3))
        self.positions = np.zeros((self.total_len, 3))
        self.rotations = np.zeros((self.total_len, self.joint_num, 3))
        self.get_offset()
#         self.get_position_rotation()
        self.get_rotation_from_position()
    def read_kinect_to_dic(self, file_path):
        with open(file_path, "r+") as f:
            data = f.readlines()
        f.close()
        self.total_len = len(data)
        for i in range(self.total_len):
            temp = {}
            frame = data[i].split(" ")
            #left leg
            temp["Pelvis"] = np.array([float(frame[0*7+i]) for i in range(7)])
            temp["LeftUpLeg"] = np.array([float(frame[12*7+i]) for i in range(7)])
            temp["LeftLeg"] = np.array([float(frame[13*7+i]) for i in range(7)])
            temp["LeftFoot"] = np.array([float(frame[14*7+i]) for i in range(7)])
            temp["LeftToeBase"] = np.array([float(frame[15*7+i]) for i in range(7)])
            #right leg
            temp["RightUpLeg"] = np.array([float(frame[16*7+i]) for i in range(7)])
            temp["RightLeg"] = np.array([float(frame[17*7+i]) for i in range(7)])
            temp["RightFoot"] = np.array([float(frame[18*7+i]) for i in range(7)])
            temp["RightToeBase"] = np.array([float(frame[19*7+i]) for i in range(7)])
            #middle
            temp["Hips"] = np.array([float(frame[0*7+i]) for i in range(7)])
            temp["Spine"] = np.array([float(frame[1*7+i]) for i in range(7)])
            temp["Spine1"] = np.array([(float(frame[1*7+i])+float(frame[20*7+i]))/2 for i in range(3)]+[float(frame[1*7+i+3]) for i in range(4)])
            temp["Spine2"] = np.array([float(frame[20*7+i]) for i in range(7)])
            temp["Neck"] = np.array([float(frame[2*7+i]) for i in range(7)])
            temp["Head"] = np.array([float(frame[3*7+i]) for i in range(7)])
            #left arm
            temp["LeftShoulder"] = np.array([float(frame[4*7+i]) for i in range(7)])
            temp["LeftArm"] = np.array([float(frame[5*7+i]) for i in range(7)])
            temp["LeftForeArm"] = np.array([float(frame[6*7+i]) for i in range(7)])
            temp["LeftHand"] = np.array([float(frame[7*7+i]) for i in range(7)])
            #right arm
            temp["RightShoulder"] = np.array([float(frame[8*7+i]) for i in range(7)])
            temp["RightArm"] = np.array([float(frame[9*7+i]) for i in range(7)])
            temp["RightForeArm"] = np.array([float(frame[10*7+i]) for i in range(7)])
            temp["RightHand"] = np.array([float(frame[11*7+i]) for i in range(7)])
            self.dic[i] = temp
    def get_offset(self):
        for i in range(self.joint_num):
            total = np.zeros((self.total_len,3))
            for frame in range(self.total_len):
                temp = self.dic[frame][self.corps_name[i]] - self.dic[frame][self.corps_name[self.topology[i]]]
                total[frame] = temp[:3]
            self.offsets[i] = np.median(total, axis = 0)*100
            
    def get_rotation_from_position(self):
        for i in range(self.total_len):
            #position
            self.positions[i] = (self.dic[i]["Pelvis"][:3]-self.dic[0]["Pelvis"][:3])*100
            #rotation
            euler = np.zeros((self.joint_num, 2))
            quater = np.zeros((self.joint_num, 4))
#             quater[0] = np.array([1., 0., 0., 0.])
            rel_quater = np.zeros_like(quater)
#             rel_quater[0] = np.array([1., 0., 0., 0.])

            for j in range(self.joint_num):
                if j == 0 or j == 9:
                    quater[j] = np.array([1., 0., 0., 0.])
                    rel_quater[j] = np.array([1., 0., 0., 0.])
                    continue
                # Get the quaternion of its parent
                q_parent = quater[self.topology[j]]

                # Initialize a quaternion encoding the relative position of the joint
                q_delta = np.zeros(4)

                # Get the relative position of the joint
                q_delta[1:] = self.dic[i][self.corps_name[j]][:3] - self.dic[i][self.corps_name[self.topology[j]]][:3]

                # Normalize to obtain a unitary vector
                q_delta /= np.linalg.norm(q_delta)

                # Express this vector in the relative coordinate system of the parent joint
                q_delta = quat_left_multiply(quat_inverse(q_parent), quat_left_multiply(q_delta, q_parent))

                # Compute the euler angles with gamma=0
                alpha = np.arctan2(q_delta[1], -q_delta[2])
                beta = np.arccos(q_delta[3])
                euler[j] = np.array([alpha, beta])   
                # Compute the corresponding relative quaternion
                rel_quater[j] = np.array([
                    np.cos(alpha/2)*np.cos(beta/2),
                    np.cos(alpha/2)*np.sin(beta/2),
                    np.sin(alpha/2)*np.sin(beta/2),
                    np.sin(alpha/2)*np.cos(beta/2)
                ])

                # Compute the corresponding absolute quaternion
                quater[j] = quat_left_multiply(q_parent, rel_quater[j])
                
            self.rotations[i][: ,:2] = np.rad2deg(euler)
            
    def get_position_rotation(self):
        for i in range(self.total_len):
            #position
            self.positions[i] = (self.dic[i]["Pelvis"][:3]-self.dic[0]["Pelvis"][:3])*100
            #rotation
            temp_ro = np.zeros((self.joint_num,3))
            end_ee = ["LeftToeBase", "RightToeBase", "Head"]
            for j in range(self.joint_num):
                if self.corps_name[j] in end_ee:
                    temp_ro[j] = np.zeros(3)
                else:
                    #Get the quaternion of its parent.
                    q_parent = self.dic[i][self.corps_name[self.topology[j]]][3:]
                    #Get the quaternion of the joint
                    q_current = self.dic[i][self.corps_name[j]][3:]
                    #Calculate the relative quaternion
                    q_relative = quat_left_multiply(q_current, quat_inverse(q_parent))
#                     print(i, self.corps_name[j], q_relative)
                    #Convert to Euler angle
                    temp_ro[j] = euler_from_quat(q_relative)
            self.rotations[i] = temp_ro
            
    def write_bvh(self, parent, offset, rotation, position, names, frametime, order, path, endsite=None):
        file = open(path, 'w')
        frame = rotation.shape[0]
        joint_num = rotation.shape[1]
#         print("parent: ",parent)
#         print("offset: ", offset)
        order = order.upper()

        file_string = 'HIERARCHY\n'

        def write_static(idx, prefix):
            nonlocal parent, offset, rotation, names, order, endsite, file_string
            if idx == 0:
                name_label = 'ROOT ' + names[idx]
                channel_label = 'CHANNELS 6 Xposition Yposition Zposition {}rotation {}rotation {}rotation'.format(*order)
            else:
                name_label = 'JOINT ' + names[idx]
                channel_label = 'CHANNELS 3 {}rotation {}rotation {}rotation'.format(*order)
            offset_label = 'OFFSET %.6f %.6f %.6f' % (offset[idx][0], offset[idx][1], offset[idx][2])

            file_string += prefix + name_label + '\n'
            file_string += prefix + '{\n'
            file_string += prefix + '\t' + offset_label + '\n'
            file_string += prefix + '\t' + channel_label + '\n'

            has_child = False
            for y in range(idx+1, rotation.shape[1]):
                if parent[y] == idx:
                    has_child = True
                    write_static(y, prefix + '\t')
            if not has_child:
                file_string += prefix + '\t' + 'End Site\n'
                file_string += prefix + '\t' + '{\n'
                file_string += prefix + '\t\t' + 'OFFSET 0 0 0\n'
                file_string += prefix + '\t' + '}\n'

            file_string += prefix + '}\n'

        write_static(0, '')

        file_string += 'MOTION\n' + 'Frames: {}\n'.format(frame) + 'Frame Time: %.8f\n' % frametime
        for i in range(frame):
            file_string += '%.6f %.6f %.6f ' % (position[i][0], position[i][1], position[i][2])
            for j in range(joint_num):
                file_string += '%.6f %.6f %.6f ' % (rotation[i][j][0], rotation[i][j][1], rotation[i][j][2])
            file_string += '\n'

        file.write(file_string)
        return file_string
    def write(self, write_path):
        a = "zxy"
        print(a)
        self.write_bvh(self.topology, self.offsets, self.rotations, self.positions, self.corps_name, 1.0/30, a, write_path)

In [3]:
a = kinect2BVH("CTK.txt")
a.write("CTK_zxy.BVH")
a.rotations[10]

C:\Users\22628\AppData\Local\Temp\ipykernel_4244\2677761903.py:100: RuntimeWarning: invalid value encountered in arccos
  beta = np.arccos(q_delta[3])


zxy


array([[   0.        ,    0.        ,    0.        ],
       [ -94.59747473,  105.17864605,    0.        ],
       [  20.2807568 ,   46.29796965,    0.        ],
       [  74.3518557 ,   89.27025745,    0.        ],
       [ 173.32781319,   56.28002767,    0.        ],
       [  93.05489554,  116.05074941,    0.        ],
       [ -12.94358783,   52.81742373,    0.        ],
       [ -80.68460115,   98.14728939,    0.        ],
       [-169.7803642 ,   82.43843361,    0.        ],
       [   0.        ,    0.        ,    0.        ],
       [ 179.05484253,   96.22310754,    0.        ],
       [  26.88515107,    2.0394261 ,    0.        ],
       [  41.9737775 ,    0.        ,    0.        ],
       [ -56.91407035,    2.44593004,    0.        ],
       [  -5.54677649,    9.56969307,    0.        ],
       [  21.34845138,   95.75564052,    0.        ],
       [ -28.52113473,   70.22079642,    0.        ],
       [ -70.36519006,   55.23132438,    0.        ],
       [ -89.4703875 ,    4.

In [5]:
alist = []
for name in a.corps_name:
    print(name)
    alist.append(a.dic[10][name][3:])
alist = np.array(alist)
print(a.dic[10])
alist

Pelvis
LeftUpLeg
LeftLeg
LeftFoot
LeftToeBase
RightUpLeg
RightLeg
RightFoot
RightToeBase
Hips
Spine
Spine1
Spine2
Neck
Head
LeftShoulder
LeftArm
LeftForeArm
LeftHand
RightShoulder
RightArm
RightForeArm
RightHand
{'Pelvis': array([ 0.316029, -0.544247,  3.07123 , -0.047392,  0.010779,  0.997367,
       -0.05383 ]), 'LeftUpLeg': array([ 0.237137, -0.537903,  3.049758,  0.057139, -0.66726 ,  0.731723,
       -0.126808]), 'LeftLeg': array([ 0.065891, -0.608917,  2.768026,  0.554786, -0.397428, -0.294837,
        0.668831]), 'LeftFoot': array([ 0.092609, -1.030478,  2.851481, -0.070962, -0.438743,  0.073678,
        0.892771]), 'LeftToeBase': array([ 0.054801, -1.087159,  2.808301,  0.      ,  0.      ,  0.      ,
        0.      ]), 'RightUpLeg': array([ 0.389443, -0.540329,  3.035292, -0.130758,  0.664309,  0.71193 ,
       -0.18642 ]), 'RightLeg': array([ 0.464061, -0.599492,  2.695029, -0.508402,  0.48729 , -0.39725 ,
        0.588446]), 'RightFoot': array([ 0.446056, -1.050501,  2.8392

array([[-4.73920e-02,  1.07790e-02,  9.97367e-01, -5.38300e-02],
       [ 5.71390e-02, -6.67260e-01,  7.31723e-01, -1.26808e-01],
       [ 5.54786e-01, -3.97428e-01, -2.94837e-01,  6.68831e-01],
       [-7.09620e-02, -4.38743e-01,  7.36780e-02,  8.92771e-01],
       [ 0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00],
       [-1.30758e-01,  6.64309e-01,  7.11930e-01, -1.86420e-01],
       [-5.08402e-01,  4.87290e-01, -3.97250e-01,  5.88446e-01],
       [ 1.01497e-01,  5.48356e-01,  1.17446e-01,  8.21712e-01],
       [ 0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00],
       [-4.73920e-02,  1.07790e-02,  9.97367e-01, -5.38300e-02],
       [-4.52890e-02,  1.06650e-02,  9.97464e-01, -5.38530e-02],
       [-4.52890e-02,  1.06650e-02,  9.97464e-01, -5.38530e-02],
       [-4.38250e-02,  3.20100e-03,  9.96576e-01, -7.00420e-02],
       [-4.41190e-02, -3.25000e-04,  9.94871e-01, -9.10230e-02],
       [ 0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00],
       [ 5.09210e-02,  7.