In [38]:
import numpy as np
from scipy.spatial.transform import Rotation as R

# Pelvis worldposition

In [58]:
position_pelvis = np.array([-0.588198, 80.405891, 0.093877])
stransmat_pelvis = np.array([[1., 0., 0., 0.],[0., 1., 0., 0.],
                             [0., 0., 1., 0.],[0., 0., 0., 1.]])
stransmat_pelvis[0, 3] = 0 #offset
stransmat_pelvis[1, 3] = 0
stransmat_pelvis[2, 3] = 0

dtransmat_pelvis = np.array([[1., 0., 0., 0.], [0., 1., 0., 0.],
                   [0., 0., 1., 0.], [0., 0., 0., 1.]])
dtransmat_pelvis[0, 3] = position_pelvis[0] #position
dtransmat_pelvis[1, 3] = position_pelvis[1]
dtransmat_pelvis[2, 3] = position_pelvis[2]


In [40]:
#rotation
rotx_pelvis = -19.801004
roty_pelvis = -82.304784
rotz_pelvis = -21.016957

Rxp = R.from_euler('x', rotx_pelvis, degrees=True).as_matrix()
Rxp = np.vstack((Rxp,[0,0,0]))
Rxp = np.hstack((Rxp,[[0],[0],[0],[1]]))
Ryp = R.from_euler('y', roty_pelvis, degrees=True).as_matrix()
Ryp = np.vstack((Ryp,[0,0,0]))
Ryp = np.hstack((Ryp,[[0],[0],[0],[1]]))
Rzp = R.from_euler('z', rotz_pelvis, degrees=True).as_matrix()
Rzp = np.vstack((Rzp,[0,0,0]))
Rzp = np.hstack((Rzp,[[0],[0],[0],[1]]))

drotmat_pelvis = np.matmul(np.matmul(Rxp,Ryp),Rzp)

In [41]:
localtoworld_pelvis = np.matmul(stransmat_pelvis,dtransmat_pelvis)
print(localtoworld_pelvis)
pelvis_trtr = np.matmul(localtoworld_pelvis,drotmat_pelvis)
print(pelvis_trtr)

[[ 1.        0.        0.       -0.588198]
 [ 0.        1.        0.       80.405891]
 [ 0.        0.        1.        0.093877]
 [ 0.        0.        0.        1.      ]]
[[ 1.24995424e-01  4.80236969e-02 -9.90994384e-01 -5.88198000e-01]
 [-2.40685332e-02  9.98680701e-01  4.53603809e-02  8.04058910e+01]
 [ 9.91865338e-01  1.81819412e-02  1.25986378e-01  9.38770000e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


# LeftupLeg worldposition

In [56]:
offset_leftupleg = np.array([8.479700, -4.795502, -0.379100])
stransmat_leftupleg = np.array([[1., 0., 0., 0.],[0., 1., 0., 0.],
                             [0., 0., 1., 0.],[0., 0., 0., 1.]])
stransmat_leftupleg[0, 3] = offset_leftupleg[0] #offset
stransmat_leftupleg[1, 3] = offset_leftupleg[1]
stransmat_leftupleg[2, 3] = offset_leftupleg[2]

rotX = -17.820706 
rotY = 14.832582 
rotZ = 9.603647

Rx = R.from_euler('x', rotX, degrees=True).as_matrix()
Ry = R.from_euler('y', rotY, degrees=True).as_matrix()
Rz = R.from_euler('z', rotZ, degrees=True).as_matrix()

drotmat_leftupleg = np.matmul(np.matmul(Rx,Ry),Rz)

In [57]:
# print(stransmat_leftupleg[0,3])
localtoworld_leftupleg = np.dot(pelvis_trtr,stransmat_leftupleg)
print(localtoworld_leftupleg)

[[ 1.24995424e-01  4.80236969e-02 -9.90994384e-01  6.17113937e-01]
 [-2.40685332e-02  9.98680701e-01  4.53603809e-02  7.53954256e+01]
 [ 9.91865338e-01  1.81819412e-02  1.25986378e-01  8.36964454e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [ ]:
0.617113937,75.39542564, 8.369644539

# Method 2

In [6]:
import numpy as np
from scipy.spatial.transform import Rotation as R
position_pelvis = np.array([-0.588198, 80.405891, 0.093877])
stransmat_pelvis = np.array([[1., 0., 0., 0.],[0., 1., 0., 0.],
                             [0., 0., 1., 0.],[0., 0., 0., 1.]])
stransmat_pelvis[0, 3] = 0 #offset
stransmat_pelvis[1, 3] = 0
stransmat_pelvis[2, 3] = 0

dtransmat_pelvis = np.array([[1., 0., 0., 0.], [0., 1., 0., 0.],
                   [0., 0., 1., 0.], [0., 0., 0., 1.]])
dtransmat_pelvis[0, 3] = position_pelvis[0] #position
dtransmat_pelvis[1, 3] = position_pelvis[1]
dtransmat_pelvis[2, 3] = position_pelvis[2]

In [7]:
#rotation
rotx_pelvis = -19.801004
roty_pelvis = -82.304784
rotz_pelvis = -21.016957

Rxp = R.from_euler('x', rotx_pelvis, degrees=True).as_matrix()
# Rxp = np.vstack((Rxp,[0,0,0]))
# Rxp = np.hstack((Rxp,[[0],[0],[0],[1]]))
Ryp = R.from_euler('y', roty_pelvis, degrees=True).as_matrix()
# Ryp = np.vstack((Ryp,[0,0,0]))
# Ryp = np.hstack((Ryp,[[0],[0],[0],[1]]))
Rzp = R.from_euler('z', rotz_pelvis, degrees=True).as_matrix()
# Rzp = np.vstack((Rzp,[0,0,0]))
# Rzp = np.hstack((Rzp,[[0],[0],[0],[1]]))

drotmat_pelvis = np.matmul(np.matmul(Rxp,Ryp),Rzp)

In [12]:
# localtoworld_pelvis = np.matmul(stransmat_pelvis,dtransmat_pelvis)
# print(localtoworld_pelvis)
localtoworld_pelvis = np.array([-0.588198, 80.405891, 0.093877])
pelvis_trtr = np.matmul(localtoworld_pelvis,drotmat_pelvis)
print(pelvis_trtr)

[-1.91566058 80.27327097  4.24196998]
